### ISSUE TITLE
Romanian translation

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-translations#25]
Merge https://github.com/Haulmont/jmix-translations/pull/24

**Comment by knstvk** [comment]
QA: please test the translation

**Comment by konyashkina** [comment]
Not translated:
- bpm
- dashboards
- imap 
- pivottable

**Core/UI:** 

Set ‘Presentation’ flag for a table (browser): <presentations auto="true"/>
Open the browser in app (e.g. Users)
Hover cursor over the presentation icon ![presentation-icon](https://user-images.githubusercontent.com/85500330/131348139-3b9113da-832f-4063-bba3-173560b9ba69.png)   and click. 
Then click Settings to expand a drop-down menu. 
There are 2 lines: ‘Save as’ and ‘Reset’. The first line is translated, but the second isn’t.
Please take a look at screenshot below.
![reset-table-presentation-settings](https://user-images.githubusercontent.com/85500330/131348284-b8c2c974-bb03-436d-8157-39f3718dbf1d.png)

### Search add-on: 
Full-text condition
Open a browser (like Users browser), click Add search condition on the top. 
Click Create button. 
Please take a look at screenshot below.

![full-text-condition](https://user-images.githubusercontent.com/85500330/131348359-9f0bc259-9456-4ef2-8775-5ebd859f9d96.png)

### Dynamics attributes add-on: 
3 fields on the ‘Calculated values and options’ tab. Please take a look at screenshot below.

![dynamic-attributes-calculated-values-and-options](https://user-images.githubusercontent.com/85500330/131348431-492bea71-8f9a-4f08-8847-5b9b224b5826.png)

**Comment by knstvk** [comment]
@sorinfederiga Could you take a look at the comments above?
Looks like we need additional efforts from you to be able to release your translation "officially".
Will you be able to support it in the future? It will require some fixes and amendments from time to time.

**Comment by sorinfederiga** [comment]
Hello @konyashkina and @knstvk,

I will try to fix the above as soon as possible and yes i am glad to help with the future releases.

Thank you,
Sorin Federiga

**Comment by knstvk** [comment]
Thanks @sorinfederiga !
We are not in a hurry, but will be great to have it in the beginning of October to be in time for release 1.1.

**Comment by konyashkina** [comment]
_Tested on_ 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3583-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)
