### ISSUE TITLE
Amend and fix Simplified Chinese translation

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-translations#7]

**Comment by glebfox** [comment]
Added new message keys and altered existing see https://github.com/Haulmont/jmix-translations/commit/a547eb730985e2d746ed104e7046775c1739ebca.

**Comment by glebfox** [comment]
Added new message keys https://github.com/Haulmont/jmix-translations/commit/377b0906661cfd476006579a4c2287139d348129
